development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:983e3a649df7219a76deedfdf54edcb4@scat.redistogo.com:10755/
  channel_prefix: message_me_app_production
